display_name: Vaani
publisher_display_name: rang
identity_name: dr.blank.vaani
logo_path: assets/icon/logo.png
capabilities: internetClient, location, microphone, webcam
languages: en-us
install_certificate: "false"